[package]
name = "clowarden"
description = "CLOWarden"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.67"

[dependencies]
anyhow = "1.0.70"
askama = "0.12.0"
async-trait = "0.1.68"
axum = { version = "0.6.12", features = ["macros"] }
base64 = "0.21.0"
clap = { version = "4.2.1", features = ["derive"] }
config = "0.13.3"
futures = "0.3.28"
hmac = "0.12.1"
hex = "0.4.3"
lazy_static = "1.4.0"
octorust = { git = "https://github.com/tegioz/third-party-api-clients.git" }
pem = "2.0.1"
regex = "1.7.3"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_yaml = "0.9.21"
sha2 = "0.10.6"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }

[dev-dependencies]
mockall = "0.11.4"
